workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 30
    environment:
      java: 17
      android: latest
    scripts:
      - name: Build debug APK
        script: |
          cd job-search
          ./gradlew assembleDebug
    artifacts:
      - job-search/app/build/outputs/apk/debug/*.apk
