workflows:
  android:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        - keystore_reference
    scripts:
      - name: Set up Gradle Wrapper
        script: |
          chmod +x ./gradlew
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
